### ISSUE TITLE
Add a text to "maps" on where to save multiplayer maps and add a button for opening that folder

### ISSUE THREAD

**Issue by Bierdeckel2** [Settlers4Modding/CommunityPatchLauncher#121]
In S4 HE the game does not automatically share maps as it was in S4GE. Because of this often players complain about crashing game when joining a hosted game. The reason is that they do no have the map.
Unfortunately there is also several folders that would be intuitive folders to save such maps, but only 1 works.

The text should contain an explanation about the above issue and the button should open the correct folder.

Additionally a link to siedler map source website might be beneficial.

**Comment by XanatosX** [comment]
The button should open a new window which looks a little bit like this:

![Map_Seite](https://user-images.githubusercontent.com/10531466/107632953-885a9080-6c67-11eb-86e5-ad24d25a7e57.JPG)
@Bierdeckel2 Thank you for visualizing it.

This new window should be inserted on the 'Maps' button which is already in place. This window will be changed in a future version
