### ISSUE TITLE
[Bug] File Logging does not created always

### ISSUE THREAD

**Issue by Ausgeben** [Settlers4Modding/CommunityPatchLauncher#130]
Some reason the file log data does not getting created some times. Maybe its in any folder that I dont know, maybe we should take the logs to documents/patch.

**Comment by Ausgeben** [comment]
Maybe add that the user name does not getting displayed or getting replaced by a text

**Comment by XanatosX** [comment]
When is the file not created? You searched for it after trying to update in the %temp% folder?

Was there an error message? Because we do not catch any error, the whole process should crash I think.

**Comment by Ausgeben** [comment]
No Error, temp was empty about this

**Comment by Ausgeben** [comment]
Weirdly it was created a time after closing the launcher (like 1-2 min), but there is another issue: he does not open the s4editorplus, the name etc was correct

**Comment by XanatosX** [comment]
What did you try to get a log file?

The editor problem should be another issue
