### ISSUE TITLE
Träger 65535

### ISSUE THREAD

**Issue by Kampfknoedel81** [Settlers4Modding/CommunityPatchLauncher#138]
Hallo!!!

Leider kann man im einzel-und Mehrspielermodus die träger nur auf 999 erhöhen ,gibt es da eine Lösung???

danke

**Comment by Ausgeben** [comment]
Hallo Kampfknödel,

normalerweise spielt man ohne träger, da diese die gleiche Funktion wie Freie Siedler haben, nur das sie keinen Job übernehmen können.

Aus diesen Grund lässt man eigentlich alle immer nur suf freie Siedler, damit man den überblick behält :)

MfG
