### ISSUE TITLE
[Feature] Add content to the README

### ISSUE THREAD

**Issue by earthwalker31** [Settlers4Modding/CommunityPatchLauncher#23]
Before making the repository public, we need a good README for the project including:

- Short introduction
- Technologies used
- Installation process and requirements
- Project status 
- Team

**Comment by XanatosX** [comment]
There is a branch for this https://github.com/Settlers4Modding/CommunityPatchLauncher/tree/feature/adding-readme-content I will try to add content to this as soon as possible

**Comment by XanatosX** [comment]
Readme ia in place
