### ISSUE TITLE
Landingpage (Startup)

### ISSUE THREAD

**Issue by Flofus** [Settlers4Modding/CommunityPatchLauncher#82]
Start landing Page is empty

![image](https://user-images.githubusercontent.com/8128268/106367500-5b42df80-6343-11eb-811b-7fc395479798.png)

**Comment by XanatosX** [comment]
What should be shown first?
The play area?

**Comment by Ausgeben** [comment]
@XanatosX news?

**Comment by XanatosX** [comment]
Yep News are a good idea, we juat need some content for the page which results in another problem

**Comment by XanatosX** [comment]
Blocked by #85

**Comment by XanatosX** [comment]
Waiting for PR #86 so that we can continue

The PR depends on https://github.com/LitzeYT/Settlers4Patch/pull/8

**Comment by XanatosX** [comment]
I think we can start with the task

**Comment by XanatosX** [comment]
Blocked by #96

**Comment by XanatosX** [comment]
Will be fixed in the next version

**Comment by XanatosX** [comment]
Should start on the news page now, please give me some feedback

**Comment by Flofus** [comment]
Worked :)
