### ISSUE TITLE
Settings Style

### ISSUE THREAD

**Issue by Flofus** [Settlers4Modding/CommunityPatchLauncher#83]
The buttons in the settings to wide

![image](https://user-images.githubusercontent.com/8128268/106367759-2d5e9a80-6345-11eb-8768-04bcbc3fee42.png)

Is it meant to be?

**Comment by XanatosX** [comment]
To fix this issue the `SettingsUserControl.xaml` must be edited I think

**Comment by XanatosX** [comment]
I think it should be enough if a maxwidht and a minwidht is getting defined for the buttons

**Comment by XanatosX** [comment]
Fixed please check it out and provide feedback

**Comment by Flofus** [comment]
Perfect
