### ISSUE TITLE
Optional Features

### ISSUE THREAD

**Issue by Flofus** [Settlers4Modding/CommunityPatchLauncher#84]
- Autosave by changing folders
- auto minimize  after starting SIV (option Marker)

**Comment by XanatosX** [comment]
Not surw if we should auto save the folder changes this would collide with the save button in my opinion

**Comment by XanatosX** [comment]
Adding a minimize function should be a quick addition

**Comment by XanatosX** [comment]
Please check this if #109 is merged and you client is up to date.

This should add the minimize on gamestart option.

**Comment by Flofus** [comment]
> Please check this if #109 is merged and you client is up to date.
> 
> This should add the minimize on gamestart option.

Checked but not working and the Setting were not saved

**Comment by XanatosX** [comment]
I can't reproduce the behavior, did you find any steps to reproduce. I did try it with a clean setting file I tried it with a already written setting file and could not reproduce.

Did you find any steps to reproduce?

**Comment by Flofus** [comment]
I think it was a bug, i cannot reproduce it now

**Comment by XanatosX** [comment]
Hmm okay I will watch this issue and if do find it again try to solve it. For now I would call it fixed :)

If you are happy with the changes please close the issue
