### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by Flofus** [Settlers4Modding/CommunityPatchLauncher#87]
Start editor from Launcher not exists

**Comment by XanatosX** [comment]
Which editor do you mean?

**Comment by Flofus** [comment]
S4Editor.exe :)

**Comment by XanatosX** [comment]
I think this should be a new menu item in the `Settle` part of the menu. Just a simple click and open it.

**Comment by XanatosX** [comment]
Should work now pöease chek it out

**Comment by XanatosX** [comment]
We need to extend this to the "Editor+" the current implementation is not that helpful

**Comment by XanatosX** [comment]
The editor will be included into the community patch DLC with this information we can implement this feature completely as soon as the dependency is included.
